//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.26 at 03:10:26 AM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ma2me.com/shortest")
package com.ma2me.shortest;
