//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 06:40:41 PM CAT 
//


package com.ma2me.shortest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shortestPathRequest" type="{http://ma2me.com/shortest}shortestPathRequest"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shortestPathRequest"
})
@XmlRootElement(name = "GetShortestPathRequest")
public class GetShortestPathRequest {

    @XmlElement(required = true)
    protected ShortestPathRequest shortestPathRequest;

    /**
     * Gets the value of the shortestPathRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ShortestPathRequest }
     *     
     */
    public ShortestPathRequest getShortestPathRequest() {
        return shortestPathRequest;
    }

    /**
     * Sets the value of the shortestPathRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortestPathRequest }
     *     
     */
    public void setShortestPathRequest(ShortestPathRequest value) {
        this.shortestPathRequest = value;
    }

}
