//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 06:40:41 PM CAT 
//


package com.ma2me.shortest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ma2me.shortest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ma2me.shortest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetShortestPathResponse }
     * 
     */
    public GetShortestPathResponse createGetShortestPathResponse() {
        return new GetShortestPathResponse();
    }

    /**
     * Create an instance of {@link ShortestPathResponse }
     * 
     */
    public ShortestPathResponse createShortestPathResponse() {
        return new ShortestPathResponse();
    }

    /**
     * Create an instance of {@link GetShortestPathRequest }
     * 
     */
    public GetShortestPathRequest createGetShortestPathRequest() {
        return new GetShortestPathRequest();
    }

    /**
     * Create an instance of {@link ShortestPathRequest }
     * 
     */
    public ShortestPathRequest createShortestPathRequest() {
        return new ShortestPathRequest();
    }

}
